# Generated by Django 3.1.7 on 2021-07-07 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0013_auto_20210611_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование типа')),
                ('short_name', models.CharField(max_length=150, verbose_name='Наименование типа')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='institutions.institutions', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Тип урока',
                'verbose_name_plural': 'Типы уроков',
                'ordering': ['name'],
            },
        ),
    ]
