# Generated by Django 4.0.2 on 2022-07-10 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_initial'),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('date', models.DateField(verbose_name='Дата урока')),
                ('topic', models.CharField(blank=True, max_length=300, null=True, verbose_name='Тема урока')),
                ('homework', models.CharField(blank=True, max_length=300, null=True, verbose_name='Домашнее задание')),
                ('class_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.classes')),
                ('date_homework', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.lessons', verbose_name='Дата дз')),
                ('subject_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.load', verbose_name='Предмет')),
            ],
        ),
        migrations.CreateModel(
            name='LessonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование типа')),
                ('short_name', models.CharField(max_length=150, verbose_name='Сокращенное наименование типа')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='institutions.institutions', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Тип урока',
                'verbose_name_plural': 'Типы уроков',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReasonSkipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('reason', models.IntegerField(choices=[(1, 'Уважительная причина'), (2, 'Неуважительная причина'), (3, 'По болезни причина')])),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.student', verbose_name='Ученик')),
            ],
        ),
        migrations.CreateModel(
            name='MarksItog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(blank=True, null=True)),
                ('itog', models.IntegerField(blank=True, null=True)),
                ('not_certified', models.IntegerField(blank=True, null=True)),
                ('load', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.load', verbose_name='Нагрузка')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.periods', verbose_name='Период')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.student', verbose_name='Ученик')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(blank=True, null=True)),
                ('mark2', models.IntegerField(blank=True, null=True)),
                ('attendance', models.IntegerField(blank=True, null=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.lessons', verbose_name='Урок')),
                ('lesson_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.lessontype', verbose_name='Тип урока')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.student', verbose_name='Ученик')),
            ],
        ),
    ]
