# Generated by Django 3.1.7 on 2021-07-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessontype',
            name='short_name',
            field=models.CharField(max_length=150, verbose_name='Сокращенное наименование типа'),
        ),
    ]
