# Generated by Django 3.1.7 on 2021-07-12 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0019_delete_lessons'),
        ('journal', '0002_auto_20210708_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('date', models.DateField(verbose_name='Дата урока')),
                ('topic', models.CharField(blank=True, max_length=300, null=True, verbose_name='Тема урока')),
                ('homework', models.CharField(blank=True, max_length=300, null=True, verbose_name='Домашнее задание')),
                ('class_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.classes')),
                ('date_homework', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.lessons', verbose_name='Дата дз')),
                ('subject_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.load', verbose_name='Предмет')),
                ('types', models.ManyToManyField(to='journal.LessonType')),
            ],
        ),
    ]
