# Generated by Django 4.0.2 on 2022-07-21 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
        ('journal', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeExams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование организации')),
                ('short_name', models.CharField(max_length=10, verbose_name='Краткое наименование')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='institutions.institutions', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Тип экзамена',
                'verbose_name_plural': 'Типы экзаменов',
                'ordering': ['name'],
            },
        ),
    ]
