# Generated by Django 4.0.2 on 2022-07-21 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
        ('journal', '0003_typeexams'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeexams',
            name='system_mark',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='institutions.systemmarks', verbose_name='Система оценивания'),
        ),
        migrations.AlterField(
            model_name='typeexams',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Наименование типа'),
        ),
        migrations.AlterField(
            model_name='typeexams',
            name='short_name',
            field=models.CharField(max_length=10, verbose_name='Сокращенное наименование типа'),
        ),
    ]
