# Generated by Django 3.1.7 on 2021-07-14 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0013_auto_20210611_1133'),
        ('classes', '0019_delete_lessons'),
        ('journal', '0004_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarksItog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(blank=True, null=True)),
                ('itog', models.IntegerField(blank=True, null=True)),
                ('not_certified', models.IntegerField(blank=True, null=True)),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.periods', verbose_name='Период')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.student', verbose_name='Ученик')),
            ],
        ),
    ]
