# Generated by Django 4.0.2 on 2022-07-21 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_typeexams_system_mark_alter_typeexams_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeexams',
            name='system_mark',
        ),
    ]
