# Generated by Django 4.0.2 on 2022-07-25 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
        ('journal', '0005_remove_typeexams_system_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='KTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], verbose_name='Номер')),
                ('name', models.CharField(max_length=300, verbose_name='Тема ктп')),
                ('subject_ktp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.subject', verbose_name='Предмет ктп')),
            ],
        ),
        migrations.CreateModel(
            name='Sections_KTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Тема ктп')),
                ('ktp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.ktp')),
            ],
        ),
    ]
