# Generated by Django 3.1.7 on 2021-07-14 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_marksitog'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksitog',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.lessons', verbose_name='Урок'),
        ),
    ]
