# Generated by Django 3.1.7 on 2021-07-14 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0019_delete_lessons'),
        ('journal', '0006_marksitog_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marksitog',
            name='lesson',
        ),
        migrations.AddField(
            model_name='marksitog',
            name='load',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.load', verbose_name='Нагрузка'),
        ),
    ]
