# Generated by Django 3.2 on 2021-07-26 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0007_auto_20210714_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Учитель'),
        ),
    ]
