# Generated by Django 4.0.2 on 2022-07-26 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
        ('journal', '0007_ktp_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='ktp',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.institutions', verbose_name='Организация'),
        ),
    ]
