# Generated by Django 4.0.2 on 2022-07-31 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_ktp_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ktp',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Тема урока'),
        ),
        migrations.CreateModel(
            name='TopiCktp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=700, verbose_name='Наименование')),
                ('hour', models.IntegerField(verbose_name='Количество часов')),
                ('homework', models.CharField(max_length=700, verbose_name='Домашнее задание')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.sections_ktp')),
            ],
        ),
    ]
