# Generated by Django 3.2 on 2021-12-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_marksitog_mark2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marksitog',
            name='mark2',
        ),
        migrations.AddField(
            model_name='marks',
            name='mark2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
