# Generated by Django 4.0.2 on 2022-07-31 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_initial'),
        ('institutions', '0001_initial'),
        ('journal', '0009_alter_ktp_name_topicktp'),
    ]

    operations = [
        migrations.AddField(
            model_name='ktp',
            name='loads',
            field=models.ManyToManyField(to='classes.Load'),
        ),
        migrations.AlterField(
            model_name='ktp',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Наименование КТП'),
        ),
        migrations.AlterField(
            model_name='ktp',
            name='subject_ktp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.subject', verbose_name='Предмет'),
        ),
    ]
