# Generated by Django 4.0.2 on 2022-08-02 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_ktp_loads_alter_ktp_name_alter_ktp_subject_ktp'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='ktp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.topicktp'),
        ),
    ]
