# Generated by Django 4.0.2 on 2022-08-10 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
        ('journal', '0011_lessons_ktp'),
    ]

    operations = [
        migrations.AddField(
            model_name='ktp',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='institutions.year', verbose_name='Учебный год'),
        ),
    ]
