# Generated by Django 4.0.2 on 2023-07-31 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0012_ktp_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='lesson_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.lessontype', verbose_name='Тип урока'),
        ),
    ]
