# Generated by Django 3.2 on 2023-09-20 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0007_alter_institutions_number_of_lessons'),
        ('journal', '0013_alter_marks_lesson_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ktp',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.year', verbose_name='Учебный год'),
        ),
    ]
