# Generated by Django 3.2 on 2024-03-07 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0014_subjecttemplate_cabinet'),
        ('journal', '0014_alter_ktp_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='cabinet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.cabinets'),
        ),
    ]
