# Generated by Django 3.2 on 2021-05-31 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0011_subgroups_class_pk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], verbose_name='Номер')),
                ('letter', models.CharField(max_length=10, verbose_name='Литер')),
                ('bell_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='institutions.bellprofile', verbose_name='Профиль звонков')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutions.institutions', verbose_name='Организация')),
                ('period_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='institutions.periodprofile', verbose_name='Профиль учебных периодов')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutions.year', verbose_name='Учебный год')),
                ('сurriculum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='institutions.сurriculum', verbose_name='Учебный план')),
            ],
        ),
        migrations.CreateModel(
            name='Subgroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование подгруппы')),
                ('class_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.classes')),
            ],
        ),
    ]
