# Generated by Django 4.0.2 on 2022-07-10 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], verbose_name='Номер')),
                ('letter', models.CharField(blank=True, max_length=10, verbose_name='Литер')),
                ('change', models.IntegerField(choices=[(1, 'Первая смена'), (2, 'Вторая смена')], default=1, verbose_name='Смена')),
            ],
            options={
                'verbose_name': 'класс',
                'verbose_name_plural': 'Классы',
                'ordering': ['class_number', 'letter'],
            },
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['subject_pk', 'subgroup'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_enrollment', models.DateField(default='2021-09-01', verbose_name='Дата зачслениия')),
            ],
            options={
                'verbose_name': 'ученик',
                'verbose_name_plural': 'Ученики',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='StudentShifting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_shift', models.IntegerField(choices=[(1, 'Зачисление'), (2, 'Отчисление'), (3, 'Перевод')])),
                ('date', models.DateField(verbose_name='Дата')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Subgroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Наименование подгруппы')),
            ],
            options={
                'ordering': ['subject_pk', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubjectTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.IntegerField(null=True)),
                ('day', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimetableTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Наименование шаблона')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Сurriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Наименование профиля')),
            ],
        ),
        migrations.CreateModel(
            name='СurriculumSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.FloatField(null=True)),
                ('class_number', models.IntegerField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.сurriculum')),
            ],
        ),
    ]
