# Generated by Django 3.2 on 2021-06-11 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0012_auto_20210531_1401'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Сurriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование профиля')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutions.institutions', verbose_name='Организация')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutions.year', verbose_name='Учебный год')),
            ],
        ),
        migrations.CreateModel(
            name='СurriculumSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField(null=True)),
                ('class_number', models.IntegerField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.сurriculum')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.subject')),
            ],
        ),
        migrations.AlterField(
            model_name='classes',
            name='сurriculum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='classes.сurriculum', verbose_name='Учебный план'),
        ),
    ]
