# Generated by Django 4.0.2 on 2022-07-10 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='сurriculumsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.subject'),
        ),
        migrations.AddField(
            model_name='сurriculum',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutions.institutions', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='сurriculum',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutions.year', verbose_name='Учебный год'),
        ),
        migrations.AddField(
            model_name='timetabletemplates',
            name='class_pk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.classes'),
        ),
        migrations.AddField(
            model_name='timetabletemplates',
            name='сurriculum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.сurriculum', verbose_name='Учебный план'),
        ),
        migrations.AddField(
            model_name='subjecttemplate',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.timetabletemplates'),
        ),
        migrations.AddField(
            model_name='subjecttemplate',
            name='subject_pk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.load', verbose_name='Предмет'),
        ),
        migrations.AddField(
            model_name='subgroups',
            name='class_pk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.classes'),
        ),
        migrations.AddField(
            model_name='subgroups',
            name='subject_pk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.сurriculumsubject', verbose_name='Предмет'),
        ),
        migrations.AddField(
            model_name='studentsubgroup',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.student', verbose_name='Ученик'),
        ),
        migrations.AddField(
            model_name='studentsubgroup',
            name='subgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.subgroups', verbose_name='Подгруппа'),
        ),
        migrations.AddField(
            model_name='studentsubgroup',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.сurriculumsubject', verbose_name='Предмет'),
        ),
        migrations.AddField(
            model_name='studentshifting',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.student', verbose_name='Ученик'),
        ),
        migrations.AddField(
            model_name='student',
            name='class_pk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.classes'),
        ),
        migrations.AddField(
            model_name='student',
            name='old_classes',
            field=models.ManyToManyField(null=True, related_name='old_classes', to='classes.Classes'),
        ),
    ]
