# Generated by Django 3.2 on 2021-06-11 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0002_auto_20210611_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='class_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Классный руководитель'),
        ),
    ]
