# Generated by Django 3.2 on 2021-06-14 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0013_auto_20210611_1133'),
        ('classes', '0003_classes_class_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgroups',
            name='subject_pk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.subject'),
        ),
    ]
