# Generated by Django 4.0.2 on 2023-07-31 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='delete_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Код удаления'),
        ),
    ]
