# Generated by Django 4.0.2 on 2023-07-31 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_student_delete_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='delete_code',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Код удаления'),
        ),
    ]
