# Generated by Django 3.1.7 on 2021-06-17 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutions', '0013_auto_20210611_1133'),
        ('classes', '0004_subgroups_subject_pk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={'ordering': ['letter', 'class_number']},
        ),
        migrations.AddField(
            model_name='subgroups',
            name='name',
            field=models.CharField(max_length=150, null=True, verbose_name='Наименование подгруппы'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='bell_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.bellprofile', verbose_name='Профиль звонков'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Классный руководитель'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='period_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.periodprofile', verbose_name='Профиль учебных периодов'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='сurriculum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.сurriculum', verbose_name='Учебный план'),
        ),
        migrations.AlterField(
            model_name='subgroups',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subgroups',
            name='subject_pk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.сurriculumsubject'),
        ),
        migrations.AlterField(
            model_name='сurriculum',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='сurriculumsubject',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
