# Generated by Django 4.0.2 on 2023-08-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_alter_student_delete_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='name_group',
            field=models.CharField(blank=True, max_length=10, verbose_name='Наименование группы'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_number',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], verbose_name='Номер'),
        ),
    ]
