# Generated by Django 3.1.7 on 2021-06-18 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_auto_20210618_0010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={'ordering': ['class_number', 'letter']},
        ),
        migrations.RemoveField(
            model_name='subgroups',
            name='title',
        ),
        migrations.AlterField(
            model_name='subgroups',
            name='subject_pk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.сurriculumsubject', verbose_name='Предмет'),
        ),
    ]
