# Generated by Django 3.1.7 on 2021-06-19 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0006_auto_20210619_0015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subgroups',
            options={'ordering': ['subject_pk', 'name']},
        ),
        migrations.CreateModel(
            name='load',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.classes')),
                ('subgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.subgroups', verbose_name='Подгруппа')),
                ('subject_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.сurriculumsubject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Классный руководитель')),
            ],
        ),
    ]
