# Generated by Django 4.0.2 on 2023-08-06 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0004_alter_subject_short_title_alter_subject_title'),
        ('classes', '0006_classes_name_group_alter_classes_class_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Наименование профессии')),
                ('class_number', models.IntegerField(blank=True, verbose_name='Срок обучения')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutions.institutions', verbose_name='Организация')),
            ],
        ),
    ]
