# Generated by Django 4.0.2 on 2023-08-06 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_professions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professions',
            old_name='class_number',
            new_name='training_period',
        ),
    ]
