# Generated by Django 4.0.2 on 2023-08-06 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_rename_class_number_professions_training_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='profession_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.professions', verbose_name='Профессия'),
        ),
    ]
