# Generated by Django 4.0.2 on 2023-08-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_classes_profession_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professions',
            name='training_period',
            field=models.CharField(blank=True, max_length=30, verbose_name='Срок обучения'),
        ),
    ]
