# Generated by Django 3.1.7 on 2021-07-02 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_auto_20210629_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetabletemplates',
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата урока')),
                ('topic', models.CharField(blank=True, max_length=300, null=True, verbose_name='Тема урока')),
                ('homework', models.CharField(blank=True, max_length=300, null=True, verbose_name='Домашнее задание')),
                ('class_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.classes')),
                ('subject_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.сurriculumsubject', verbose_name='Предмет')),
            ],
        ),
    ]
