# Generated by Django 4.0.2 on 2023-08-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_alter_professions_training_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professions',
            name='training_period',
            field=models.CharField(max_length=30, verbose_name='Срок обучения'),
        ),
    ]
