# Generated by Django 3.1.7 on 2021-07-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_auto_20210702_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата урока'),
        ),
    ]
