# Generated by Django 3.1.7 on 2021-07-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0011_auto_20210702_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='date',
            field=models.DateField(verbose_name='Дата урока'),
        ),
    ]
