# Generated by Django 3.2 on 2024-03-04 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0012_cabinets_floors'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinets',
            name='floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.floors'),
        ),
    ]
