# Generated by Django 3.1.7 on 2021-07-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0014_auto_20210705_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='date_homework',
            field=models.DateField(blank=True, null=True, verbose_name='Дата дз'),
        ),
    ]
