# Generated by Django 3.1.7 on 2021-07-08 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0015_lessons_date_homework'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='date_homework',
        ),
    ]
