# Generated by Django 3.1.7 on 2021-07-08 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0016_remove_lessons_date_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='date_homework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.lessons', verbose_name='Дата дз'),
        ),
    ]
