# Generated by Django 3.1.7 on 2021-07-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20210708_1634'),
        ('classes', '0017_lessons_date_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='types',
            field=models.ManyToManyField(to='journal.LessonType'),
        ),
    ]
