# Generated by Django 3.1.7 on 2021-07-12 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0018_lessons_types'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lessons',
        ),
    ]
