# Generated by Django 3.2 on 2021-07-26 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0021_subjecttemplate_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjecttemplate',
            name='teacher',
        ),
    ]
