# Generated by Django 3.2 on 2021-11-25 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0022_remove_subjecttemplate_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='сurriculum',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Наименование профиля'),
        ),
        migrations.CreateModel(
            name='StudentSubgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.student', verbose_name='Ученик')),
                ('subgroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.subgroups', verbose_name='Подгруппа')),
            ],
        ),
    ]
