# Generated by Django 3.2 on 2021-11-26 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0023_auto_20211125_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubgroup',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.сurriculumsubject', verbose_name='Предмет'),
        ),
    ]
