# Generated by Django 3.2 on 2021-11-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0024_studentsubgroup_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='сurriculumsubject',
            name='hour',
            field=models.FloatField(null=True),
        ),
    ]
