# Generated by Django 4.0.2 on 2022-07-06 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0024_studentsubgroup_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={'ordering': ['class_number', 'letter'], 'verbose_name': 'класс', 'verbose_name_plural': 'Классы'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['user'], 'verbose_name': 'ученик', 'verbose_name_plural': 'Ученики'},
        ),
        migrations.AddField(
            model_name='classes',
            name='change',
            field=models.IntegerField(choices=[(1, 'Первая смена'), (2, 'Вторая смена')], default=1, verbose_name='Смена'),
        ),
        migrations.AddField(
            model_name='student',
            name='arсhive_classes',
            field=models.ManyToManyField(null=True, related_name='old_classes', to='classes.Classes'),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_enrollment',
            field=models.DateField(default='2021-09-01', verbose_name='Дата зачслениия'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='letter',
            field=models.CharField(blank=True, max_length=10, verbose_name='Литер'),
        ),
        migrations.AlterField(
            model_name='сurriculumsubject',
            name='hour',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='StudentShifting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_shift', models.IntegerField(choices=[(1, 'Зачисление'), (2, 'Отчисление'), (3, 'Перевод')])),
                ('date', models.DateField(verbose_name='Дата')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.student', verbose_name='Ученик')),
            ],
        ),
    ]
