# Generated by Django 3.2 on 2021-12-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0025_alter_сurriculumsubject_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='change',
            field=models.IntegerField(choices=[(1, 'Первая смена'), (2, 'Вторая смена')], default=1),
        ),
    ]
