# Generated by Django 3.2 on 2021-12-17 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0026_classes_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='change',
            field=models.IntegerField(choices=[(1, 'Первая смена'), (2, 'Вторая смена')], default=1, verbose_name='Смена'),
        ),
        migrations.CreateModel(
            name='StudentShifting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_shift', models.IntegerField(choices=[(1, 'Зачисление'), (2, 'Отчисление'), (3, 'Перевод')])),
                ('date', models.DateTimeField(verbose_name='Дата Отчисления')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.student', verbose_name='Ученик')),
            ],
        ),
    ]
