[program:busel]
command=/home/ilnur/venv/bin/gunicorn mysite.wsgi:application -c /home/ilnur/busel/config/gunicorn.conf.py
directory=/home/ilnur/busel/
autorestart=true
user=ilnur
redirect_stderr=true
stdout_logfile=/home/ilnur/busel/logs/debug.log

