# Generated by Django 3.2 on 2021-05-05 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_auto_20210505_1740'),
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernet',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/%Y/%m/%d/', verbose_name='Фотография пользователя'),
        ),
        migrations.AddField(
            model_name='usernet',
            name='institutions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.institutions'),
        ),
        migrations.AddField(
            model_name='usernet',
            name='middle_name',
            field=models.CharField(max_length=150, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='usernet',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='usernet',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
    ]
