# Generated by Django 3.2 on 2022-01-02 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_auto_20220102_1704'),
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Имя шаблона')),
                ('file', models.FileField(blank=True, upload_to='templates/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='usernet',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AddField(
            model_name='usernet',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/%Y/%m/%d/', verbose_name='Фотография пользователя'),
        ),
        migrations.AddField(
            model_name='usernet',
            name='birth_day',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='usernet',
            name='gender',
            field=models.CharField(max_length=150, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='usernet',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.institutions'),
        ),
        migrations.AddField(
            model_name='usernet',
            name='middle_name',
            field=models.CharField(max_length=150, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='usernet',
            name='position',
            field=models.CharField(max_length=150, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='usernet',
            name='registration',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='usernet',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='usernet',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
    ]
