# Generated by Django 4.0.2 on 2022-07-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernet',
            name='code',
            field=models.CharField(max_length=150, null=True, verbose_name='Пригласительный код'),
        ),
    ]
