# Generated by Django 4.0.2 on 2023-07-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_usernet_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernet',
            name='mail_conf',
            field=models.BooleanField(default=False),
        ),
    ]
