# Generated by Django 3.2 on 2021-05-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0011_subgroups_class_pk'),
        ('user_account', '0003_rename_institutions_usernet_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernet',
            name='classes',
            field=models.ManyToManyField(null=True, to='institutions.Classes', verbose_name='Классы'),
        ),
    ]
