# Generated by Django 4.0.2 on 2023-07-31 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_alter_institutions_departmental_organization_and_more'),
        ('user_account', '0004_historicalusernet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usernet',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='usernet',
            name='code',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Пригласительный код'),
        ),
        migrations.AlterField(
            model_name='usernet',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.institutions', verbose_name='Организация'),
        ),
        migrations.AlterUniqueTogether(
            name='usernet',
            unique_together={('email',)},
        ),
        migrations.DeleteModel(
            name='HistoricalUserNet',
        ),
    ]
