# Generated by Django 3.2 on 2021-05-13 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0011_subgroups_class_pk'),
        ('user_account', '0004_usernet_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernet',
            name='classes',
        ),
        migrations.AddField(
            model_name='usernet',
            name='classes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='institutions.classes', verbose_name='Классы'),
        ),
    ]
