# Generated by Django 3.2 on 2021-05-31 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('user_account', '0005_auto_20210513_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernet',
            name='classes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='classes.classes', verbose_name='Классы'),
        ),
    ]
