# Generated by Django 4.0.2 on 2023-08-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0006_auditentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditentry',
            name='time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Последнее редактирование'),
        ),
    ]
