# Generated by Django 3.1.7 on 2021-06-25 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0007_remove_usernet_classes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usernet',
            options={'ordering': ['last_name', 'first_name']},
        ),
    ]
