# Generated by Django 3.2 on 2023-09-21 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0007_auditentry_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usernet',
            unique_together=set(),
        ),
    ]
