# Generated by Django 3.1.7 on 2021-07-03 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0008_auto_20210625_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernet',
            name='birth_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
