# Generated by Django 3.1.7 on 2021-07-05 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0009_usernet_birth_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernet',
            name='birth_day',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
