# Generated by Django 3.1.7 on 2021-07-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0010_auto_20210705_0447'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Имя шаблона')),
                ('file', models.FileField(blank=True, upload_to='templates/')),
            ],
        ),
    ]
