# Generated by Django 3.1.7 on 2021-07-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0011_filetemplates'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernet',
            name='gender',
            field=models.CharField(choices=[(1, 'мужской'), (2, 'женский')], max_length=150, null=True, verbose_name='Пол'),
        ),
    ]
