# Generated by Django 3.1.7 on 2021-07-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0012_usernet_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernet',
            name='gender',
            field=models.CharField(max_length=150, null=True, verbose_name='Пол'),
        ),
    ]
