# Generated by Django 3.2 on 2021-07-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0013_auto_20210712_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernet',
            name='registration',
            field=models.BooleanField(null=True),
        ),
    ]
