# Generated by Django 3.2 on 2021-12-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0014_usernet_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernet',
            name='position',
            field=models.CharField(max_length=150, null=True, verbose_name='Должность'),
        ),
    ]
