# Generated by Django 3.2 on 2021-05-12 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_auto_20210505_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernet',
            old_name='institutions',
            new_name='institution',
        ),
    ]
