# Generated by Django 3.1.7 on 2021-07-05 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0013_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='subject_pk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.load', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='subjecttemplate',
            name='subject_pk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.load', verbose_name='Предмет'),
        ),
    ]
