[program:busel]
command=/home/ilnur/venv/bin/gunicorn mysite.wsgi:application -c /home/ilnur/mysite/config/gunicorn.conf.py
directory=/home/ilnur/mysite
autorestart=true
user=myuser
redirect_stderr=true
stdout_logfile=/home/ilnur/mysite/logs/debug.log