# Generated by Django 3.2 on 2021-05-05 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BellProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование профиля')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Профиль учебного периода')),
                ('typePeriod', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='institutions',
            options={'ordering': ['-pk'], 'verbose_name': 'Организацию', 'verbose_name_plural': 'Организации'},
        ),
        migrations.AlterModelOptions(
            name='year',
            options={'ordering': ['-pk'], 'verbose_name': 'Учебный год', 'verbose_name_plural': 'Учебные года'},
        ),
        migrations.CreateModel(
            name='TypeInstitutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Тип организации')),
                ('group', models.ManyToManyField(null=True, to='auth.Group')),
            ],
            options={
                'verbose_name': 'Тип организации',
                'verbose_name_plural': 'Типы организаций',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование предмета')),
                ('short_title', models.CharField(max_length=150, null=True, verbose_name='Краткое наименование предмета')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.institutions')),
            ],
        ),
        migrations.CreateModel(
            name='Periods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='Дата начала учебного периода')),
                ('end', models.DateField(verbose_name='Дата окончания учебного периода')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.periodprofile', verbose_name='Профиль учебного периода')),
            ],
        ),
        migrations.AddField(
            model_name='periodprofile',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutions.institutions', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='periodprofile',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutions.year', verbose_name='Учебный год'),
        ),
        migrations.CreateModel(
            name='BellTimetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('lesson', models.IntegerField(null=True)),
                ('day', models.IntegerField(null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.bellprofile', verbose_name='Профиль')),
            ],
        ),
        migrations.AddField(
            model_name='bellprofile',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutions.institutions', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='institutions',
            name='typeInstitutions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='institutions.typeinstitutions', verbose_name='Тип'),
        ),
    ]
