# Generated by Django 3.2 on 2021-06-11 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20210611_1133'),
        ('institutions', '0012_auto_20210531_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='сurriculumsubject',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='сurriculumsubject',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Сurriculum',
        ),
        migrations.DeleteModel(
            name='СurriculumSubject',
        ),
    ]
