# Generated by Django 3.1.7 on 2021-03-30 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование учебного года')),
                ('start', models.DateField(verbose_name='Дата начала учебного года')),
                ('end', models.DateField(verbose_name='Дата окончания учебного года')),
            ],
        ),
        migrations.CreateModel(
            name='Institutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование организации')),
                ('short_title', models.CharField(max_length=150, verbose_name='Краткое наименование организации')),
                ('photo', models.ImageField(null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutions.year', verbose_name='Учебный год')),
            ],
        ),
    ]
