# Generated by Django 4.0.2 on 2022-07-10 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BellProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование профиля')),
            ],
            options={
                'verbose_name': 'Расписание звонков',
                'verbose_name_plural': 'Профили расписания звонков',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Institutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование организации')),
                ('short_title', models.CharField(max_length=50, verbose_name='Краткое наименование')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('last_edit', models.DateTimeField(auto_now=True, null=True, verbose_name='Последнее редактирование')),
                ('is_active', models.BooleanField(default=True)),
                ('lim', models.IntegerField(default=0)),
                ('departmental_organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.institutions', verbose_name='Ведомственная организация')),
            ],
            options={
                'verbose_name': 'Организацию',
                'verbose_name_plural': 'Организации',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='KindInstitutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Вид организации')),
            ],
            options={
                'verbose_name': 'Вид организации',
                'verbose_name_plural': 'Виды организаций',
            },
        ),
        migrations.CreateModel(
            name='PeriodProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Профиль учебного периода')),
                ('typePeriod', models.IntegerField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutions.institutions', verbose_name='Организация')),
            ],
        ),
        migrations.CreateModel(
            name='SystemMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('min_mark', models.IntegerField()),
                ('max_mark', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование учебного года')),
                ('start', models.DateField(verbose_name='Дата начала учебного года')),
                ('end', models.DateField(verbose_name='Дата окончания учебного года')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Учебный год',
                'verbose_name_plural': 'Учебные года',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='TypeInstitutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Тип организации')),
                ('group', models.ManyToManyField(null=True, to='auth.Group')),
            ],
            options={
                'verbose_name': 'Тип организации',
                'verbose_name_plural': 'Типы организаций',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование предмета')),
                ('short_title', models.CharField(max_length=150, null=True, verbose_name='Краткое наименование предмета')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.institutions')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Periods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='Дата начала учебного периода')),
                ('end', models.DateField(verbose_name='Дата окончания учебного периода')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.periodprofile', verbose_name='Профиль учебного периода')),
            ],
        ),
        migrations.AddField(
            model_name='periodprofile',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutions.year', verbose_name='Учебный год'),
        ),
        migrations.AddField(
            model_name='institutions',
            name='kindInstitutions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='institutions.kindinstitutions', verbose_name='Вид'),
        ),
        migrations.AddField(
            model_name='institutions',
            name='system_mark',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='institutions.systemmarks', verbose_name='Система оценивания'),
        ),
        migrations.AddField(
            model_name='institutions',
            name='typeInstitutions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='institutions.typeinstitutions', verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='institutions',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutions.year', verbose_name='Учебный год'),
        ),
        migrations.CreateModel(
            name='BellTimetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('lesson', models.IntegerField(null=True)),
                ('day', models.IntegerField(null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.bellprofile', verbose_name='Профиль')),
            ],
        ),
        migrations.AddField(
            model_name='bellprofile',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutions.institutions', verbose_name='Организация'),
        ),
    ]
