# Generated by Django 4.0.2 on 2023-07-15 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutions',
            name='departmental_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.institutions', verbose_name='Ведомственная организация'),
        ),
        migrations.AlterField(
            model_name='institutions',
            name='kindInstitutions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='institutions.kindinstitutions', verbose_name='Вид'),
        ),
    ]
