# Generated by Django 4.0.2 on 2023-08-06 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_alter_institutions_departmental_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='type_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.typeinstitutions'),
        ),
    ]
