# Generated by Django 4.0.2 on 2023-08-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_subject_type_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='short_title',
            field=models.CharField(max_length=150, null=True, verbose_name='Краткое наименование'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Наименование'),
        ),
    ]
