# Generated by Django 3.2 on 2021-05-09 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_auto_20210509_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='СurriculumSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.IntegerField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.сurriculum')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.subject')),
            ],
        ),
    ]
