# Generated by Django 4.0.2 on 2023-08-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0004_alter_subject_short_title_alter_subject_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutions',
            name='number_of_lessons',
            field=models.IntegerField(default=8),
        ),
    ]
