# Generated by Django 3.2 on 2021-05-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0004_сurriculumsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='сurriculumsubject',
            name='hour',
            field=models.IntegerField(null=True),
        ),
    ]
