# Generated by Django 3.2 on 2021-05-10 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_сurriculumsubject_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.IntegerField()),
                ('letter', models.CharField(max_length=10)),
                ('bell_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.bellprofile', verbose_name='Профиль звонков')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutions.institutions', verbose_name='Организация')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutions.year', verbose_name='Учебный год')),
                ('сurriculum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutions.сurriculum', verbose_name='Учебный план')),
            ],
        ),
    ]
