# Generated by Django 4.0.2 on 2023-08-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_institutions_number_of_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutions',
            name='second_shift',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='institutions',
            name='number_of_lessons',
            field=models.IntegerField(default=8, verbose_name='Количество уроков в расписании'),
        ),
    ]
