# Generated by Django 3.2 on 2021-05-11 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0006_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='period_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.periodprofile', verbose_name='Профиль учебных периодов'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='bell_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.bellprofile', verbose_name='Профиль звонков'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_number',
            field=models.IntegerField(verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='letter',
            field=models.CharField(max_length=10, verbose_name='Литер'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='сurriculum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='institutions.сurriculum', verbose_name='Учебный план'),
        ),
    ]
