# Generated by Django 3.2 on 2023-09-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0006_institutions_second_shift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutions',
            name='number_of_lessons',
            field=models.IntegerField(default=8, verbose_name='Количество уроков (занятий) в расписании'),
        ),
    ]
