# Generated by Django 3.2 on 2024-02-24 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0007_alter_institutions_number_of_lessons'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectInstituions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование организации')),
                ('short_title', models.CharField(max_length=50, verbose_name='Краткое наименование')),
                ('city', models.CharField(max_length=150, verbose_name='Город')),
                ('email', models.CharField(max_length=150, verbose_name='Почта')),
                ('phone', models.CharField(max_length=150, verbose_name='Телефон')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('surname', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=150, null=True, verbose_name='Отчество')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutions.institutions', verbose_name='Управляющая организация')),
                ('kindInstitutions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='institutions.kindinstitutions', verbose_name='Вид')),
                ('typeInstitutions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='institutions.typeinstitutions', verbose_name='Тип')),
            ],
        ),
    ]
