# Generated by Django 3.2 on 2021-05-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0007_auto_20210511_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='class_number',
            field=models.IntegerField(choices=[('', 1), ('', '2'), ('', '3'), ('', '4'), ('', '5'), ('', '6'), ('', '7'), ('', '8'), ('', '9'), ('', '10'), ('', '11')], verbose_name='Номер'),
        ),
    ]
