# Generated by Django 3.2 on 2021-05-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0008_alter_classes_class_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subgroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование подгруппы')),
            ],
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_number',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], verbose_name='Номер'),
        ),
    ]
