# Generated by Django 3.2 on 2024-02-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0008_connectinstituions'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectinstituions',
            name='comment',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Комментарий'),
        ),
    ]
