# Generated by Django 3.2 on 2024-02-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0009_connectinstituions_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectinstituions',
            name='birthday',
            field=models.CharField(max_length=150, null=True, verbose_name='Дата рождения'),
        ),
    ]
