# Generated by Django 3.2 on 2021-05-12 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0009_auto_20210512_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='bell_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='institutions.bellprofile', verbose_name='Профиль звонков'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='period_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='institutions.periodprofile', verbose_name='Профиль учебных периодов'),
        ),
    ]
