# Generated by Django 3.2 on 2024-02-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0010_connectinstituions_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectinstituions',
            name='comment',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Комментарий'),
        ),
    ]
