# Generated by Django 3.2 on 2021-05-13 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0010_auto_20210512_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgroups',
            name='class_pk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.classes'),
        ),
    ]
