# Generated by Django 3.2 on 2024-02-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0011_alter_connectinstituions_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectinstituions',
            name='short_title',
            field=models.CharField(max_length=350, verbose_name='Краткое наименование'),
        ),
        migrations.AlterField(
            model_name='connectinstituions',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Наименование организации'),
        ),
    ]
