# Generated by Django 3.2 on 2021-05-31 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0006_alter_usernet_classes'),
        ('institutions', '0011_subgroups_class_pk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subgroups',
            name='class_pk',
        ),
        migrations.DeleteModel(
            name='Classes',
        ),
        migrations.DeleteModel(
            name='Subgroups',
        ),
    ]
