# Generated by Django 3.2 on 2024-02-25 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0012_auto_20240225_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectinstituions',
            old_name='kindInstitutions',
            new_name='kindOfInstitutions',
        ),
    ]
