# Generated by Django 3.2 on 2024-02-25 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0013_rename_kindinstitutions_connectinstituions_kindofinstitutions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectinstituions',
            old_name='kindOfInstitutions',
            new_name='kindInstitutions',
        ),
    ]
