# Generated by Django 3.2 on 2021-07-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0013_auto_20210611_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutions',
            name='last_edit',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Последнее редактирование'),
        ),
    ]
