# Generated by Django 3.2 on 2024-03-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0014_rename_kindofinstitutions_connectinstituions_kindinstitutions'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectinstituions',
            name='inn',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='institutions',
            name='inn',
            field=models.IntegerField(null=True),
        ),
    ]
