# Generated by Django 3.2 on 2021-07-25 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0014_institutions_last_edit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('min_mark', models.IntegerField()),
                ('max_mark', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='institutions',
            name='system_mark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='institutions.systemmarks', verbose_name='Система оценивания'),
        ),
    ]
