# Generated by Django 3.2 on 2024-03-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0015_auto_20240301_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectinstituions',
            name='inn',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='institutions',
            name='inn',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
