# Generated by Django 3.2 on 2021-07-25 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0015_auto_20210725_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutions',
            name='system_mark',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='institutions.systemmarks', verbose_name='Система оценивания'),
        ),
    ]
