# Generated by Django 3.2 on 2021-07-25 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0016_alter_institutions_system_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutions',
            name='system_mark',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='institutions.systemmarks', verbose_name='Система оценивания'),
        ),
    ]
