# Generated by Django 3.2 on 2021-12-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0017_alter_institutions_system_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutions',
            name='short_title',
            field=models.CharField(max_length=50, verbose_name='Краткое наименование'),
        ),
    ]
