# Generated by Django 4.0.2 on 2022-03-17 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0017_alter_institutions_system_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='KindInstitutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Вид организации')),
            ],
            options={
                'verbose_name': 'Вид организации',
                'verbose_name_plural': 'Виды организаций',
            },
        ),
        migrations.AlterModelOptions(
            name='bellprofile',
            options={'ordering': ['-pk'], 'verbose_name': 'Расписание звонков', 'verbose_name_plural': 'Профили расписания звонков'},
        ),
        migrations.AddField(
            model_name='institutions',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='institutions',
            name='short_title',
            field=models.CharField(max_length=50, verbose_name='Краткое наименование'),
        ),
        migrations.AddField(
            model_name='institutions',
            name='kindInstitutions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='institutions.kindinstitutions', verbose_name='Вид'),
        ),
    ]