# Generated by Django 4.0.2 on 2022-07-06 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0018_kindinstitutions_alter_bellprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutions',
            name='departmental_organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.institutions', verbose_name='Ведомственная организация'),
        ),
        migrations.AddField(
            model_name='year',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активен'),
        ),
    ]
