# Generated by Django 4.0.2 on 2022-06-29 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0019_department_institutions_departmental_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutions',
            name='departmental_organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.institutions', verbose_name='Ведомственная организация'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
