# Generated by Django 4.0.2 on 2022-07-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0020_alter_institutions_departmental_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
