# Generated by Django 4.0.2 on 2022-07-05 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0021_year_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutions',
            name='departmental_organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.institutions', verbose_name='Ведомственная организация'),
        ),
        migrations.AlterField(
            model_name='year',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активен'),
        ),
    ]
